### ISSUE TITLE
Last else block does not work.

### ISSUE THREAD

**Issue by jfrader** [rodw/common-dustjs-helpers#4] opened 2017-05-10 17:38 UTC
Example:

```
{#data.authors}
          "@type": "Person",
          "name": "{.title}"
        {@last}.{:else},{/last}
{/data.authors}
```

Only shows the dot, not the comma.

**Comment by rodw** [comment] 2017-06-27 21:27
Can you provide a more complete example of this?  I'm not able to reproduce this problem (short of having a list with only one element, in which case the `{:else}` block should not execute).

There is a pre-existing test case that demonstrates that the `{:else}` block does indeed work for `@last`. The snippet (from `test-common-dustjs-helpers`)  illustrates the inputs and outputs:

```
  '@last':{
    source:   'before|{#list}{@last}LAST!{:else}{.} is not last. {/last}{/list}|after',
    context:  { list: ['one','two','three','four','five'] },
    expected: 'before|one is not last. two is not last. three is not last. four is not last. LAST!|after'
  },
```

Moreover, by inspection you can see that the same method handles the logic for rendering `{:else}` block is exactly the same for `@first` and `@last`, so it is unusual that one would work but the other would not.

**Comment by rodw** [comment] 2019-09-26 19:19
Not reproducible. Closing.

**Closed as completed by rodw** 2019-09-26 19:19 UTC
Labels: invalid
