### ISSUE TITLE
Instantiation Issue

### ISSUE THREAD

**Issue by jmsherry** [rodw/common-dustjs-helpers#1] opened 2014-03-10 22:23 UTC
Hi there,
When I do your instantiation method:

```
var helpers = new require("common-dustjs-helpers").CommonDustjsHelpers();
var dust = require("dustjs"); // or "dustjs-linkedin"
helpers.export_helpers_to(dust);
```

I get "TypeError: Cannot call method 'export_helpers_to' of undefined"

When I run the first line and then console.dir it, I get:

{ CommonDustjsHelpers: { [Function: CommonDustjsHelpers] dust: null } }

So it returns an object which has a property 'CommonDustjsHelpers' which is a ?? Is that an anonymous function logged out? (...rather than those being array markers)

Can you help??

Thanks. :)

**Comment by cocomartian** [comment] 2014-04-24 14:07
I encounter this error too. Have you resolved this error?

**Comment by cocomartian** [comment] 2014-04-24 14:40
NVM, I just copied the necessary code that I need instead of installing the entire module.

**Comment by framp** [comment] 2014-06-13 18:16
You're supposed to write `new (require("common-dustjs-helpers").CommonDustjsHelpers)()`

The worst thing is that this module doesn't conform to the API established by dustjs-helpers

I'm not interested in embarking in this adventure, but here it is the js code generated from common-dustjs-helpers following the dustjs-helpers API: https://gist.github.com/framp/a9cef5f74679a70c9dc8
Hope it's useful

**Comment by jmsherry** [comment] 2014-06-13 18:48
@framp Yeah, I think I might fork it if I get a chance and do something with it... I think it's a bit of an afterthought; I think someone dumped the code here and was going to work on it, then didn't...

@emanuelsaringan Sorry, I didn't see your reply... I just did the same as you really... :)

**Comment by paulmsmith** [comment] 2014-07-09 10:20
Thanks @framp that got these up and running for me, however sounds like this is not quite right. Where should that Gist be copied to? Forgive me, I'm rather new the node/gulp/dust land.

**Comment by paulmsmith** [comment] 2014-07-09 10:25
Ha, infact @framp I've just added it to your very own gulp-dust-html plugin! :) I'm essentially cobbling things together but I'm: 

![screen shot 2014-07-09 at 11 24 23](https://cloud.githubusercontent.com/assets/57055/3523011/39785ac2-0753-11e4-8ab6-ba1089357aee.png)

**Comment by framp** [comment] 2014-07-09 16:35
Well, @paulmsmith the gist is supposed to be required in place of common-dustjs-helpers (and I'm happy to hear you like gulp-dust-html! :) ).
You should be able to `require('./gist.js')` to populate dustjs-linkedin helpers object.

Actually I stopped fixing the package as soon as I noticed half of the helpers were of no use to me (and others were conflicting with dustjs-helpers). I'm not sure every helper will work (and probably won't).

FYI I just extracted the repeat helper (which was the only useful one to me) and published it as a npm module.
You can use it like this:

```
var dust = require('dustjs-linkedin');
dust.helpers = require('dustjs-helpers').helpers; //HACK: due to a dustjs-helpers bug
require('dustjs-helper-repeat');
```

**Comment by paulmsmith** [comment] 2014-07-10 08:56
Thanks for replying.

I only really needed the repeat helper too. Sadly I think dust is not quite ready for me. I was trying to do an @if inside a partial that was being repeated and it just wan't being processed. It would repeat the partial and had the data that was being passed into it but the @if just seemed not to fire/run.

I want to move away from Ruby/Rake and .ERB templating but it's still just too good compared to the rest.

I'm now planning to leverage gulp combined with the middleman ruby gem. 

If you have a sample project where you're using your gulp-dust-html and your helper, it might be a light bulb moment for a newbie like me. :)

**Comment by framp** [comment] 2014-07-10 09:59
Thanks for the report, there was a bug which prevented the dust.helpers property to get extended in gulp-dust-html.

Check out this little project: https://github.com/framp/gulp-basic
It should be a good starting point (despite not being release-worthy) - and I've added an example with dustjs-repeat-helper

**Comment by paulmsmith** [comment] 2014-07-10 10:35
Brilliant. Will check it out now. :) Thanks so much!

**Comment by dvic** [comment] 2015-02-26 16:34
Doesn't my PR #3 fix this issue by the way?

**Comment by rodw** [comment] 2016-05-03 22:45
Sorry @jmsherry, somehow this issue escaped my notice. 

@framp has it correct - the reason you encounter the error is the order of operations.  You want 

```
new (require("common-dustjs-helpers").CommonDustjsHelpers)()
```

not

```
new require("common-dustjs-helpers").CommonDustjsHelpers()
```

so that the `new` applies to the class name, not the `require` function.

That said, the most recent version of this module (1.4.1) makes this a little easier. 

The recommended way to register the helpers with Dust is as follows:

```
require("common-dustjs-helpers").exportTo(dust);
```

where `dust` is a Dust.js instance obtained via `require("dustjs")` or `require("dustjs-linkedin")` or whatever.

**Comment by rodw** [comment] 2016-05-03 23:15
@framp regarding your comment:

> The worst thing is that this module doesn't conform to the API established by dustjs-helpers

I'm not sure I'm familiar with the API you're referring to.

To be frank I don't use dustjs-helpers very often, but when I do, I do this:

```
var dust = require("dustjs-helpers")
```

which gives me a Dust instance with the dustjs-helpers helpers already registered.

In fact, that's part of the reason that common-dustjs-helpers _doesn't_ instantiate its own instance of Dust, so that you can use it with the original "dustjs", with "dustjs-linkedin", with "dustjs-helpers" (which is dustjs-linkedin plus the LinkedIn helpers), or with some other dustjs variant that I'm not even aware of.

Rather than try to anticipate the specific configuration of Dustjs you want to inject the common helpers into, we have the user pass in the dust instance as a parameter.

With the latest version of common-dustjs-helpers, that looks like this:

```
var dust = require("dustjs-linkedin");
require("common-dustjs-helpers").exportTo(dust);
```

or, if you want to the "dustjs-helpers" as well as the "common-dustjs-helpers":

```
var dust = require("dustjs-helpers");
require("common-dustjs-helpers").exportTo(dust);
```

etc. 

Since the root issue that this ticket describes has been addressed I'm going to close it, but I am interested in trying to address the concern you raised.

If I'm reading your gist properly, I _think_ you're looking for the ability to do something like this:

```
var dust = require("common-dustjs-helpers");
```

to obtain (presumably) an instance of dustjs with the common-helpers already registered.

Is that correct?

We _could_ make something like that happen pretty readily (e.g., it is basically:

```
var  dust = require("common-dustjs-helpers").exportTo(require("dustjs-linkedin"));
```

with a minor change to `exportTo` to return the dust instance passed in for easier chaining.)   

However, I'm not entirely sure that's the _right_ approach.  The import style used by `dustjs-helpers` doesn't seem to work well when there is more than one helper module involved, and certainly doesn't scale to a situation where there might be half-a-dozen different helper modules to mix and match.

For example, your gist seems to be based on `dustjs-helpers` rather than just `dustjs-linkedin`, but there are many circumstances where I explicitly _don't_ want the dustjs-helpers exposed since historically they tended to break with the original dustjs philosophy of templates not having side effects.  (Although looking at dustjs-helpers just now to find an example of this I notice that the latest version of dustjs-helpers is largely @first, @last and a different syntax but similar functionality for @if.)

In any event, I'm happy to try to incorporate or even implement the changes you're seeking, I'm just not sure what those changes are.

Please feel free to create pull request with the changes you're proposing or, if you're not sure what those changes would be, just create a new issue describing in more detail the "API" you're looking for.

Thanks.

**Closed as completed by rodw** 2016-05-03 23:15 UTC

**Comment by framp** [comment] 2016-05-04 10:00
Hey @rodw, I was referring to how you export your module.

``` javascript
(typeof exports !== 'undefined' ? module.exports = require('dustjs-linkedin') : dust))
```

When I'm using a dust helper I want it to be exported like all the other dust helpers, so that I can use them in the same way.
Other examples: https://github.com/rragan/dust-motes/blob/master/src/helpers/html/layout/layout.js
Or any other helper in that that repo.

``` javascript
var dust = require('dustjs-linkedin');
dust.helpers = require('dustjs-helpers').helpers; //HACK needed at the time because they broke dustjs-helpers
require('dustjs-helper-repeat');
require('dustjs-any-other-helper');
```

This is not possible with your package.

That said the issue is quite old, there are tons of template engines with expose a better designed API than dust, I'm not using your collection of helpers and I'm more for a modular approach (eg: one module per helper) - so I'm not going to push this forward.

Cheers.
